theme: jekyll-theme-minimal
title: Osama Ata's homepage
description: As a Contracts Engineer at Archirodon Group N.V., Osama manages a portfolio of contracts in Tabuk region, Saudi Arabia, for some of the most ambitious and visionary projects in the world, such as NEOM and the Red Sea Project. 

He is responsible for contract drafting, reviewing, and negotiations, as well as correspondence management, providing contractual advice and strategies, and claims analysis and preparation.

He has a solid academic background in civil engineering and contracts management. He has a BSc in Civil Engineering, a PGCert in Structural Engineering, and a PGDip in Contracts Management and Administration. 

He is also a member of the Chartered Institute of Arbitrators (MCIArb) and the Saudi Council of Engineers (SCE).

He is applying his skills and knowledge to deliver high-quality results to ensure customer satisfaction. He is always eager to learn new things and challenge himself in a dynamic and fast-paced environment.
