theme: jekyll-theme-minimal
title: Osama Ata's homepage
description: As a Contracts Engineer at Archirodon Group N.V., Osama manages a portfolio of contracts in Tabuk region, Saudi Arabia, for some of the most ambitious and visionary projects in the world, such as NEOM and the Red Sea Project.
